cache_size: 1024
node_address: <NODE_RPC>
dingtalk_token: <DINGTALK_TOKEN>
services:
  constructor:
    enabled: true
    config:
      tokens:
        <TOKEN_GROUP>:
          - <TOKEN_ADDR>
  transfer:
    enabled: true
    config:
      wallets:
        - <ADDR>
      threshold_value: <VALUE as USDT>
